# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'freq.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_freq(object):
    def setupUi(self, freq):
        freq.setObjectName("freq")
        freq.resize(290, 218)
        freq.setMinimumSize(QtCore.QSize(290, 218))
        freq.setMaximumSize(QtCore.QSize(290, 218))
        freq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox = QtWidgets.QSpinBox(freq)
        self.spinBox.setGeometry(QtCore.QRect(90, 80, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(freq)
        self.pushButton.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("background-image: url(./assert/灰2.png);\n"
"font: 14pt \"Candara\";")
        self.label = QtWidgets.QLabel(freq)
        self.label.setGeometry(QtCore.QRect(0, 0, 161, 41))
        self.label.setStyleSheet("font: 87 20pt \"Arial Black\";")
        self.label.setObjectName("label")

        self.retranslateUi(freq)
        self.pushButton.clicked.connect(freq.frequency_sure_pushbutton) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(freq)

    def retranslateUi(self, freq):
        _translate = QtCore.QCoreApplication.translate
        freq.setWindowTitle(_translate("freq", "设置频率"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./assert/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        freq.setWindowIcon(icon)
        self.pushButton.setText(_translate("freq", "确定"))
        self.label.setText(_translate("freq", "频率：秒"))
