# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signin_server(object):
    def setupUi(self, signin_server):
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(signin_server.sizePolicy().hasHeightForWidth())
        signin_server.setSizePolicy(sizePolicy)
        signin_server.setObjectName("signin_server")
        signin_server.resize(780, 520)
        signin_server.setMinimumSize(QtCore.QSize(780, 520))
        signin_server.setMaximumSize(QtCore.QSize(1500, 1200))
        signin_server.setStyleSheet("background-image: url(./assert/2.png);")
        self.centralwidget = QtWidgets.QWidget(signin_server)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("background-image: url(./assert/2.jg);"
                                 "font: 87 20pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 75, -1, 75)
        self.verticalLayout.setSpacing(50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.username.setFont(font)
        self.username.setStyleSheet("background-image: url(./assert/2.jpg);"
"border:1px groove gray;border-radius:\n"
"7px;padding:2px 4px;\n"
"font: 10pt \"Candara\";")
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.password.setFont(font)
        self.password.setStyleSheet("background-image: url(./assert/2.jpg);"
"border:1px groove gray;border-radius:\n"
"7px;padding:2px 4px;\n"
"font: 10pt \"Candara\";")
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet(
"background-image: url(./assert/灰2.png);\n"
"font: 14pt \"Candara\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet(
"background-image: url(./assert/灰2.png);\n"
"font: 14pt \"Candara\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 5)
        self.verticalLayout_2.setStretch(2, 2)
        signin_server.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(signin_server)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 21))
        self.menubar.setObjectName("menubar")
        signin_server.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(signin_server)
        self.statusbar.setObjectName("statusbar")
        signin_server.setStatusBar(self.statusbar)

        self.retranslateUi(signin_server)
        self.pushButton.clicked.connect(signin_server.signin_pushbutton) # type: ignore
        self.pushButton_2.clicked.connect(signin_server.signup_pushbutton) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(signin_server)

    def retranslateUi(self, signin_server):
        _translate = QtCore.QCoreApplication.translate
        signin_server.setWindowTitle(_translate("signin_server", "登录注册"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./assert/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signin_server.setWindowIcon(icon)
        self.label.setText(_translate("signin_server", "Login now"))
        self.username.setPlaceholderText(_translate("signin_server", "Please input your Id"))
        self.password.setPlaceholderText(_translate("signin_server", "Please input your Password"))
        self.pushButton.setText(_translate("signin_server", "登录"))
        self.pushButton_2.setText(_translate("signin_server", "注册"))
