# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup_server(object):
    def setupUi(self, signup_server):
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(signup_server.sizePolicy().hasHeightForWidth())
        signup_server.setSizePolicy(sizePolicy)
        signup_server.setObjectName("signup_server")
        signup_server.resize(520, 500)
        signup_server.setMinimumSize(QtCore.QSize(520, 500))
        signup_server.setMaximumSize(QtCore.QSize(1500, 1200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(signup_server)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(signup_server)
        self.label.setStyleSheet("font: 87 20pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(signup_server)
        self.label_2.setStyleSheet("font: 87 20pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(signup_server)
        self.label_3.setStyleSheet("font: 10pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.username = QtWidgets.QLineEdit(signup_server)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.label_4 = QtWidgets.QLabel(signup_server)
        self.label_4.setStyleSheet("font: 10pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.password = QtWidgets.QLineEdit(signup_server)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.label_5 = QtWidgets.QLabel(signup_server)
        self.label_5.setStyleSheet("font: 10pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.surepassword = QtWidgets.QLineEdit(signup_server)
        self.surepassword.setObjectName("surepassword")
        self.verticalLayout.addWidget(self.surepassword)
        self.label_6 = QtWidgets.QLabel(signup_server)
        self.label_6.setStyleSheet("font: 10pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(signup_server)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_7 = QtWidgets.QLabel(signup_server)
        self.label_7.setStyleSheet("font: 10pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)

        self.lineEdit_2 = QtWidgets.QLineEdit(signup_server)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        # self.label_8 = QtWidgets.QLabel(signup_server)
        # self.label_8.setStyleSheet("font: 10pt \"Arial\";")
        # self.label_8.setObjectName("label_8")
        # self.verticalLayout.addWidget(self.label_8)
        # self.lineEdit_3 = QtWidgets.QLineEdit(signup_server)
        # self.lineEdit_3.setEnabled(True)
        # self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        # self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.lineEdit_3.setObjectName("lineEdit_3")
        # self.verticalLayout.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(signup_server)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.52, y1:1, x2:0.54, y2:0, \n"
"stop:0.0112994 rgba(64, 145, 252, 255), \n"
"stop:1 rgba(255, 255, 255, 255));\n"
"background-image: url(./assert/灰2.png);\n"
"font: 14pt \"Candara\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(signup_server)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.52, y1:1, x2:0.54, y2:0, \n"
"stop:0.0112994 rgba(64, 145, 252, 255), \n"
"stop:1 rgba(255, 255, 255, 255));\n"
"background-image: url(./assert/灰2.png);\n"
"font: 14pt \"Candara\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 8)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(4, 2)

        self.retranslateUi(signup_server)
        self.pushButton.clicked.connect(signup_server.signup_sure_pushbutton) # type: ignore
        self.pushButton_2.clicked.connect(signup_server.back_signin_pushbutton) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(signup_server)

    def retranslateUi(self, signup_server):
        _translate = QtCore.QCoreApplication.translate
        signup_server.setWindowTitle(_translate("signup_server", "注册"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./assert/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signup_server.setWindowIcon(icon)
        self.label.setText(_translate("signup_server", "Hello"))
        self.label_2.setText(_translate("signup_server", "Welcome to us!"))
        self.label_3.setText(_translate("signup_server", "Username"))
        self.label_4.setText(_translate("signup_server", "Password"))
        self.label_5.setText(_translate("signup_server", "Ensure your password"))
        self.label_6.setText(_translate("signup_server", "Ip address"))
        self.label_7.setText(_translate("signup_server", "Mac address"))
        # self.label_8.setText(_translate("signup_server", "Binding code"))
        self.pushButton.setText(_translate("signup_server", "注册"))
        self.pushButton_2.setText(_translate("signup_server", "返回登录"))
